"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/makeconf.py']
DATA_FILES = []
OPTIONS = {
        'dist_dir': 'build',
        'argv_emulation': True,
        'semi_standalone': True,
        'packages': ['PySide', 'json'],
        }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
